' Macros for Entity/Class diagrams
' Author:           Matthew Billington
' Modified date:    20-FEB-2020

hide circle
skinparam linetype ortho

' Functions defining Tables 
' usage: 
'   TABLE(table_name)
'   TABLE(table_name, alias)

!unquoted function TABLE($name)
!return entity "**$name **" as $name << (T, white) >>
!endfunction

!unquoted function TABLE($name, $alias)
!return entity "**$name //($alias)//**" as $name << (T, white) >>
!endfunction

!unquoted function VIEW($name)
!return entity "**$name **" as $name << (V, green) >>
!endfunction

!unquoted function VIEW($name, $alias)
!return entity "**$name //($alias)//**" as $name << (V, green) >>
!endfunction

!unquoted function OBJECT($name)
!return class "**$name **" as $name << (O, white) >>
!endfunction

!unquoted function OBJECT($name, $alias)
!return class "**$name //($alias)//**" as $name << (O, white) >>
!endfunction

!unquoted function NOTFINAL_OBJECT($name)
!return abstract OBJECT($name)
!endfunction

!unquoted function NOTFINAL_OBJECT($name, $alias)
!return abstract OBJECT($name, $alias)
!endfunction

' Column functions

' Primary key
!unquoted function PK($column)
!return + [pk] $column
!endfunction

' Foreign key
!unquoted function PK($column)
!return # [fk] $column
!endfunction

