' Macros for Entity/Class diagrams
' Author:           Matthew Billington
' Modified date:    20-FEB-2020

hide circle
skinparam linetype ortho

' procedures defining Tables 
' usage: 
'   TABLE(table_name)
'   TABLE(table_name, alias)

!unquoted procedure TABLE($name)
entity "**$name **" as $name << (T, white) >>
!endprocedure

!unquoted procedure TABLE($name, $alias)
entity "**$name //($alias)//**" as $name << (T, white) >>
!endprocedure

!unquoted procedure VIEW($name)
entity "**$name **" as $name << (V, green) >>
!endprocedure

!unquoted procedure VIEW($name, $alias)
entity "**$name //($alias)//**" as $name << (V, green) >>
!endprocedure

!unquoted procedure OBJECT($name)
class "**$name **" as $name << (O, white) >>
!endprocedure

!unquoted procedure OBJECT($name, $alias)
class "**$name //($alias)//**" as $name << (O, white) >>
!endprocedure

!unquoted procedure NOTFINAL_OBJECT($name)
abstract OBJECT($name)
!endprocedure

!unquoted procedure NOTFINAL_OBJECT($name, $alias)
abstract OBJECT($name, $alias)
!endprocedure

' Column procedures

' Primary key
!unquoted procedure PK($column)
+ [pk] $column
!endprocedure

' Foreign key
!unquoted procedure PK($column)
# [fk] $column
!endprocedure

